### PR TITLE
Added new actions

### PR DESCRIPTION
**Pull request by sabaatworld**
This pull request is for adding the following actions: on_min_max_brightness, on_max_min_brightness, on_min_max_color_temp, on_max_min_color_temp.

These are something that I needed and thought it would be best to implement in controllerx. This should not impact any existing setups. Please check out the docs to see the intended purpose. I was able to test out the actions with E1810 IKEA controller (Z2M) but could not test out generating the docs. There shouldn't be any errors though.

### CODE REVIEW

**Comment by sabaatworld** [comment]
don't merge this yet. performing some tests.

**Comment by sabaatworld** [comment]
Tested! Everything seems to work as expected.

**Comment by xaviml** [comment]
Hi @sabaatworld,

Thank you for the PR. It looks good to me, but I would like to add some integration tests for this feature. I will add them in your branch and merge this away! :)

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @sabaatworld,

I added some integration tests and refactor the code a bit to be more clear. I have also considered the light state for an edge case it was missed.

Regards,
Xavi M.

**Comment by sabaatworld** [comment]
I like your version more. It's much cleaner! Thanks :)

**Pull request merged**
