### PR TITLE
feat(device): add IKEA E2001/E2002 STYRBAR with ZHA support.

### PR DESCRIPTION
**Pull request by Langthjem**
Sorry if I missed something in regards of the PR/docs - this is my first OS contribution.
Integration live tested with E2002 controller in my own setup.

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @Langthjem ,

Thank you for the PR, but I just realised that the E2001/E2002 is already supported with the name of W2049 which is the name it had before I believe. It is probably a good idea to change the name.

Could you please confirm that W2059 works for you?

Documrntation for this controller can be found here: https://xaviml.github.io/controllerx/controllers/W2049

Thanks,
Xavi M.

**Comment by Langthjem** [comment]
I can confirm that W2049LightController covers the same functionality.
I would suggest that the W2049LightController and W2049MediaPlayerController are renamed or commented to remove the confusion in model naming.

**Comment by xaviml** [comment]
Hi @Langthjem,

Sorry for the time you put on this controller. I created following PR that deprecates W2049 and renames it to E2002: https://github.com/xaviml/controllerx/pull/509

It is stated in the notes of the device that the mapping also works for E2001.

Regards,
Xavi M.

**Comment by Langthjem** [comment]
Don't worry about it. I enjoyed (trying) to contribute. Just happy you put so much effort into this project.

**Pull request closed without merging**
