### PR TITLE
Add advanced toggle actions to the light controller

### LINKED ISSUE #124: [FEATURE REQUEST] TOGGLE_FULL_BRIGHTNESS
# Feature Request

### Is your feature request related to a problem?

I have a Home Assistant automation for my lights that reacts to a motion sensor. When no motion is detected for a certain amount of time, the lights get dimmed to 50% for a few minutes, then turned off automatically. This leaves the last set brightness at 50%, so turning them on later using my remote control (IKEA 5-Button Remote with combined on/off button) will always turn them back on to only 50% brightness.

### Describe the solution / feature you'd like

I would love to have a TOGGLE_FULL_BRIGHTNESS action that will turn off the light of it is currently on and turn it on at full brightness if it is currently off.

### Describe alternatives you've considered

Using the existing ON_FULL_BRIGHTNESS action will not allow me to manually turn off the lights using the toggle button on the remote. If there is another way to tell the lights to always turn on at full brightness, I might consider that.

### PR DESCRIPTION
**Pull request by kroimon**
This introduces the following actions: toggle_full_brightness, toggle_full_white_value, toggle_full_color_temp, toggle_min_brightness, toggle_min_white_value and toggle_min_color_temp.

This reduces the need for duplication of apps as suggested in the corresponding feature request #124.

Resolves #124.

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @kroimon,

First of all, sorry for the delay in responding to this PR. Secondly, thank you for your contribution. I agree with you that this will help to not duplicate configurations for something as simple as this. So I think it is worth including this feature to the codebase.

However, there are a couple of this to change before merging this PR:
1.- I see that you check the state of the light to know if `off or `set_value` should be called. Although I believe that this work and you tried yourself, I proposed to call the toggle function by passing the attribute with the max and min value. This way we don't need to check the state of the light and HA will check this with the toggle service. The toggle_min would look something like:

```python
@action
async def toggle_min(self, attribute: str) -> None:
    stepper = self.automatic_steppers[attribute]
    if isinstance(stepper, MinMaxStepper):
        min_ = stepper.minmax.min
        await self.toggle(**{attribute: min_})
```

However, since this code will need to be repeated in the `toggle_max` and it is also repeated in `set_value`. I suggest extracting a function that given a fraction and the attribute, it returns the computed value by knowing the max and min value for that attribute.

2.- We will need to add these new predefined actions to the documentation (`docs/others/custom-controllers.md`).


Having said this 3 points, I 'm able to fix this in the `kroimon:toggle_advanced` branch if you want me to. At the same time, I would be adding tests for this new feature.

Regards,
Xavi M.

**Comment by kroimon** [comment]
Hi @xaviml,

thanks for your feedback!
I wasn't aware that you can set the brightness with the `light.toggle` service, that really makes things easier by moving the on/off check into home assistant itself.

I don't really think that introducing another utility function is justified for the new three-liner functions. I feel like leaving them like they are now makes it easier to understand what is happening.

Please be aware that the changes I just pushed are currently not yet tested. I will test them this evening and report back.

**Comment by htvekov** [comment]
Hi' @kroimon & @xaviml 

AFAIR  toggle (off) with brightness: x won't raise annoying issues as by error restoring bulbs to brightness: x if turned on  via light.turn_on instead.

Both Ikea bulbs via z2m integration and Hue lights via HA Hue bridge integration should all behave perfectly doing it like this.
Transition attributes on the other hand... 👽😱🤯💀😎

Looking forward to this PR.
Will certainly minimize my number of apps by quite a few 👍

**Comment by xaviml** [comment]
Hi @htvekov ,

Thank you for pointing this out. The function toggle already handles the logic for the transition problem we have had in the pass, so this should work as expected no matter the integration.

Thanks @kroimon for the changes. Let me know if you try it out to make sure it works. I will add some unit tests to this branch before submitting the PR.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @kroimon,

I added tests to this feature and I could not push the code to your branch, so I put it in ControllerX and created PR #145.

This PR is closed in favor of #145.

**Pull request closed without merging**
