### PR TITLE
Add a switch controller and E1743 implementation

### LINKED ISSUE #65: Allow controlling outlets
# Allow controlling outlets

### Describe the solution / feature you'd like

I'd like to control outlets as easily as lights

Meaning the config snippet should be as small as possible if I just want to map the on/off buttons of my remote to the outlet.

### Describe alternatives you've considered

Though I haven't tried yet, I guess this can be achieved more verbosely with a custom controller calling services.

### Additional context

The IKEA smart outlet (fr: https://www.ikea.com/fr/fr/p/tradfri-prise-connectee-20364476/) is cheap and can be bought with a E1743 switch.
It's exposed as a switch in home assistant.

It would be nice to load all these devices in ZHA and pair them with controllerx.

I don't know how hard it would be, but I'm willing to contribute, if someone could point me in the right direction for where to start! 😀

### PR DESCRIPTION
**Pull request by Crocmagnon**
Closes #65 

Hey @xaviml, is this what you had in mind?

### CODE REVIEW

**Comment by Crocmagnon** [comment]
Currently working on the docs after having added some tests

**Comment by Crocmagnon** [comment]
I managed to test it on my current installation, works fine. I'm curious how you live test new versions of controllerx in appdaemon side by side with a stable install, if at all.

**Comment by Crocmagnon** [comment]
We could also add a "toggle" mode in which no matter which button you press it toggles the switch. But I think I read on your docs or somewhere that you only want the default behavior of the device.

**Comment by xaviml** [comment]
That is exactly what I had in mind, indeed :) Thank you for your PR. Regarding the testing environment, unfortunately, I cannot test for every single device and combination that you can do with them physically. I test manually that my set up keeps working as expected (by copying the folder in my HA instance) and then also that the test I have in place they all pass. Some of them are unitary tests, but others make sure that the configuration is written in a way that ControllerX understands, so we avoid mistakes in runtime.

I will merge this PR into dev and it will be shipped in the next release 2.5.0 maybe this week or the next one. I am also under development in something to add type annotations and better logging.

**Comment by Crocmagnon** [comment]
> I cannot test for every single device and combination that you can do with them physically

Yes of course, I was asking in order to improve the testing in my environment 😉

> I test manually that my set up keeps working as expected (by copying the folder in my HA instance)

Thanks 👍

**Pull request merged**
