### PR TITLE
Swapping CONT with LONG

### PR DESCRIPTION
**Pull request by hvorragend**

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @hvorragend,

When is `PRESS_CONT` fired? The release action of `PRESS_CONT` is `PRESS_LONG_RELEASE`? This is important since all hold actions need a release one.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Also, if `PRES_CONT` is the hold action, when is `PRESS_LONG` fired?

**Comment by hvorragend** [comment]
If I hold the button, first it appears once(!) PRESS_LONG.
During pressing the PRESS_CONT is fired multiple times. 
Releasing the button fires a PRESS_LONG_RELEASE which stops the dimming action. 

That's the way I have used it in FHEM and HA before. 
Weird, but with this pull request I can dim all lights without own mappings.

**Comment by xaviml** [comment]
> If I hold the button, first it appears once(!) PRESS_LONG.
During pressing the PRESS_CONT is fired multiple times.

If this is the case, this PR is not needed. PRESS_LONG is the one that should call the hold actions since it needs to be called once. What is the reason for this PR then?

ControllerX already calls periodically your device (light, media player) and changes their attributes (brightness, volume, etc). So between a hold and release action, ControllerX periodically changes the brightness of your light. You can change the frequency of the change and the steps with `delay` and `automatic_steps`.

**Comment by hvorragend** [comment]
I thought that we dim the lights with each new event. But your loop-solution dims smoother.

**Pull request closed without merging**
