### PR TITLE
Update WXKG07LM.yml

### PR DESCRIPTION
**Pull request by jant90**
Fixed a few mistakes in the documentation regarding ZHA action types for this controller

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @jant90,

Thanks for the fix in the documentation. Do you happen to have this controller integrated with ZHA? Could you please confirm these are the mappings? Especially "both_long press", "left_long press" and "right_long press". It is not normal to have a space in the event, but I was not sure about it.

I will merge this straight away.

Regards,
Xavi M.

**Comment by jant90** [comment]
Yes, they really show up with a space, this confused me as well so maybe put a warning in the docs? Also I was afraid this wouldn't work in YAML markup or something, but this is working fine:
```yaml
  actions:
    - left_single
    - left_double
    - left_long press
  mapping:
    left_single:
      action: toggle
    left_long press:
      action: sync
```

Here is an example from the event viewer:
```json
    "event_type": "zha_event",
    "data": {
        "device_ieee": "x",
        "unique_id": "x",
        "device_id": "x",
        "endpoint_id": 1,
        "cluster_id": 18,
        "command": "left_long press",
        "args": {
            "button": "left",
            "press_type": "long press",
            "attr_id": 85,
            "value": 0
        }
    }
```

**Comment by xaviml** [comment]
Thank you @jant90 for the response back :) After merging your PR, I quoted all the ZHA events, so it is clear that it is the whole string. In the YAML you can also quoted, so it is clear it goes together:
```yaml
actions:
    - left_single
    - left_double
    - left_long press
  mapping:
    "left_single":
      action: toggle
    "left_long press":
      action: sync
```

Cheers,

**Comment by jant90** [comment]
Thanks! That looks clear to me :).

One more (pretty unrelated) question: what's the meaning of the "350ms delay" mentioned after the light controller part for pretty much every controller in the docs?

I'm asking because I noticed a hard-coded delay/latency of about 350ms in my Aqara (WXKG07LM) and Mijia (WXKG01LM) controllers that I don't see in my Hue Dimmer switch, yet the docs do mention a 350ms delay for that controller as well.

**Pull request merged**
