### PR TITLE
WIP: Added ZHA support for Philips929002398602LightController

### PR DESCRIPTION
**Pull request by cznewt**

### CODE REVIEW

**Comment by xaviml** [comment]
Thank you @cznewt  for the PR. Let me know once the PR is ready to be reviewed, I see you changed it to "work in progress".

**Comment by ScratMan** [comment]
Hi, how to test this PR ? I own two Hue Dimmer V2 (model 9290023986), I copied the added content to the <ha_config_folder>/appdaemon/apps/controllerx/cx_devices/philips.py and created the following app in my docker/appdaemon/conf/apps/apps.yaml

```
plafonnier_chambre_apolline:
  module: controllerx
  class: Philips929002398602LightController
  controller: 00:17:88:01:09:aa:62:86
  integration: zha
  automatic_steps: 10
  light: light.lampe_bureau_gauche_391098fe_level_light_color_on_off
```

But it doesn't work. The app appears as terminated in the appdaemon apps dashboard. HA still receives the button events, but nothing happens. When using standard automations the remote works fine, but I'd like to make the long press on brightness button control the light's brightness level smoothly.

**Comment by ScratMan** [comment]
Nevermind, the issue was due to wrong installation of AppDaemon. After fixing the install I could make it work, but the device class should be changed as the OFF button of the Hue Dimmer V1 became a HUE button on Hue Dimmer V2 which is used in Hue ecosystem to change the scenes between Read, Relax, Concentrate and Energize (looks lime some preset colors). The ON button is now used for ON/OFF.

image

So I changed the class to reflect these changes:
```
    def get_zha_actions_mapping(self) -> DefaultActionsMapping:
        return {
            "off_long_release": Light.RELEASE,
            "off_hold": Light.HOLD_COLOR_DOWN,
            "off_short_release": Light.CLICK_COLOR_UP,
            "down_long_release": Light.RELEASE,
            "down_hold": Light.HOLD_BRIGHTNESS_DOWN,
            "down_short_release": Light.CLICK_BRIGHTNESS_DOWN,
            "up_long_release": Light.RELEASE,
            "up_hold": Light.HOLD_BRIGHTNESS_UP,
            "up_short_release": Light.CLICK_BRIGHTNESS_UP,
            "on_long_release": Light.RELEASE,
            "on_hold": Light.TOGGLE,
            "on_short_release": Light.TOGGLE,
        }
```

It's working really well with these changes.

**Comment by xaviml** [comment]
Hi @ScratMan ,

Thank you for the detailed explanation. I will change @cznewt PR to reflect your changes as well as change the default mapping for the Z2M and deCONZ since it is not correct either.

Regards,
Xavi M.

**Comment by ScratMan** [comment]
> wouldn't it make sense to change "on_hold" to "Light.HOLD_COLOR_UP", instead of "Light.TOGGLE". What do you think?

I thought about it when changing the file, but IMHO as the hue button is already assigned to color change up and down mapped to click and hold, having a hold color up for the ON button seems useless.

**Comment by xaviml** [comment]
Hi @ScratMan ,

You are right, the power button when held either can do nothing or turn off all the lights at home according to this review: https://youtu.be/2N8TD81KSAY?t=252. Therefore, I will implement your suggested mapping.

Thanks!

**Comment by xaviml** [comment]
Hi @ScratMan ,

This device can be now tested on [ControllerX v4.25.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.25.0b0).

Regards,
Xavi M.

**Pull request merged**
