### PR TITLE
Add support for Terncy devices under ZHA

### PR DESCRIPTION
**Pull request by ilarrain**

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @ilarrain,

Thank you for the contribution :) I see you that you mentioned in the title "Terncy devices". Does this mean that the same mapping works for:

- https://www.zigbee2mqtt.io/devices/TERNCY-PP01.html
- https://www.zigbee2mqtt.io/devices/TERNCY-SD01.html

I know that your contribution is for ZHA, but I always take the name of the models from z2m documentation.

I will pull your changes and fix the errors of the pipeline and add the documentation as well.

Regards,
Xavi M.

**Comment by ilarrain** [comment]
It does ;)
I own, and have tested, both devices.

I didn't find a way to implement the rotate action on the knob in ControllerX, only the button presses. The rotate action reports the rotation event, with the number of steps as an attribute.

BTW, I submitted the ZHA quirk implementation, partly based on the Z2M one: https://github.com/zigpy/zha-device-handlers/commits/dev/zhaquirks/terncy

The Z2M implementation should be simple (action -> single, double, triple...), but I can't test it, as I have migrated to ZHA.

Thanks for the fixes.

**Comment by xaviml** [comment]
Hi @ilarrain,

Thanks for the reply. Could you send a couple or 3 examples when the knob is rotated? I think we will need to add that logic in the get_action function. Does it report a stop rotation event?

I will create two different classes anyway for both controllers just for maintainability purposes.

Regards,
Xavi M.

**Comment by ilarrain** [comment]
No problem.

**Clockwise rotation 3 steps:**
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:13:3b:38:ac",
        "unique_id": "00:0d:6f:00:13:3b:38:ac:1:0xfccc",
        "device_id": "7efe7171098b11ebb4a67bd6cc287de0",
        "endpoint_id": 1,
        "cluster_id": 64716,
        "command": "rotate_right",
        "args": {
            "steps": 3
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-06T17:54:29.997605+00:00",
    "context": {
        "id": "fb289f8d0dd8c9658d7b50b8b596b091",
        "parent_id": null,
        "user_id": null
    }
}
```
**Counterclockwise rotation 9 steps:**
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:13:3b:38:ac",
        "unique_id": "00:0d:6f:00:13:3b:38:ac:1:0xfccc",
        "device_id": "7efe7171098b11ebb4a67bd6cc287de0",
        "endpoint_id": 1,
        "cluster_id": 64716,
        "command": "rotate_left",
        "args": {
            "steps": 9
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-06T17:54:25.490359+00:00",
    "context": {
        "id": "ed7ae9f505782a54aceb250396af3185",
        "parent_id": null,
        "user_id": null
    }
}
```
**Counterclockwise rotation 64 steps (more than 2 full rotations):**
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:13:3b:38:ac",
        "unique_id": "00:0d:6f:00:13:3b:38:ac:1:0xfccc",
        "device_id": "7efe7171098b11ebb4a67bd6cc287de0",
        "endpoint_id": 1,
        "cluster_id": 64716,
        "command": "rotate_left",
        "args": {
            "steps": 64
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-06T18:18:35.946887+00:00",
    "context": {
        "id": "75993bfa2483cb0e504bbb452b91cf7c",
        "parent_id": null,
        "user_id": null
    }
}
```

The Z2M implementation is [pretty similar](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L5075):
```
     terncy_knob: {
        cluster: 'manuSpecificClusterAduroSmart',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (typeof msg.data['27'] === 'number') {
                return {
                    direction: (msg.data['27'] > 0 ? 'clockwise' : 'counterclockwise'),
                    number: (Math.abs(msg.data['27']) / 12),
                };
            }
        },
    },
```
Only the attributes have different names.

The device reports rotation events as an attribute report, with (number of steps * 12) as the value (negative for CCW rotations, positive for CW rotations), so it's not possible to report the start rotation, nor the stop rotation event, and neither of the implementations do (ZHA or Z2M).

A full rotation (360°) is 30 steps.

Right now, I have implemented the rotation as an automation directly in HA, as follows:
```
alias: Dimmer sala (Terncy Knob)
description: ''
trigger:
  - device_id: 7efe7171098b11ebb4a67bd6cc287de0
    domain: zha
    platform: device
    type: device_rotated
    subtype: right
  - device_id: 7efe7171098b11ebb4a67bd6cc287de0
    domain: zha
    platform: device
    type: device_rotated
    subtype: left
condition: []
action:
  - service: light.turn_on
    data:
      brightness_step_pct: >-
        {{ 3 * trigger.event.data.args.steps if trigger.event.data.command ==
        "rotate_right" else -3 * trigger.event.data.args.steps}}
    entity_id: light.sala
mode: single
```

**Comment by xaviml** [comment]
Thanks for the info. I will add then the rotate_left and rotate_right to the mapping and it will increment the brightness as it was being clicked. We have the same for the xiaomi cube since it does not report the rotation_stop either.

I will keep you updated with the changes. Thank you :)

**Comment by ilarrain** [comment]
@xaviml 
I think implementing it as a click is not functional, as any rotation will have the same effect, regardless of the magnitude (steps).
Most users expect a full rotation right (CW) to increment the brightness to 100%, and a full rotation left (CCW) to turn off the lights.
IMHO, if the steps value can't be taken into account, it's better to leave the rotation unimplemented.

**Comment by xaviml** [comment]
Hi @ilarrain,

I understand. I will see if I am able to take the parameters into account. As of now, predefined actions are defined as string and it does not allow to pass any parameters. This is something I would like to change (see #78), so I might introduce this for this controller.

In case of not being able to take the rotation steps into account, I will not add the rotation left and right into account.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hey @ilarrain,

I changed your PR to add 2 classes for your controllers and also the documentation.

Regarding the code, I did not add the rotations at the end, since I need to think this through. And also, the 5th click I changed to 50% color temp since 4 and 5 clicks were doing the same, 50% brightness.

I will merge the PR once I am ready to deploy the next version which will be soon.

Regards,
Xavi M.

**Pull request merged**
