### PR TITLE
Sonos/Symfonisk display - ESPHome

### PR DESCRIPTION
**Pull request by htvekov**
Hi' Xavi

Here we go !! 🚀
Documentation v1.0 for Sonos display.

I'm not absolute sure I'm doing this PR correctly ?
Anyway, there should be 3 files in total
1 jpg file, 1 'homemade' TTF file and the documentation as md text file.
Are the links in text for picture and TTF file changed dynamically upon merge or do you need to alter manually ?

If you have the time, please take a brief look at documentation so I can edit and remove any obvious errors.
I've looked at this text for so many hours now that I'm completely 'blind' for spotting errors that perhaps have been there since start 🙂

Thank you in advance, Xavi

Ciao !

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @htvekov :)

Thank you for the documentation. I will look at it and merge probably next week. Everything looks okay, just that the jpg file is missing in the PR. You can attach in here and I will get my head around to stick it in.

Thanks :)

**Comment by htvekov** [comment]
Hi' Xavi.

I've apparently only uploaded the jpg file to dev branch... 🙄
Still have a lot to learn 😁
Added jpeg file to master branch now and commited to PR

**Comment by xaviml** [comment]
Hi @htvekov,

Are all changes ready to merge? Once it is ready, I will merge and make sure everything looks as it should be.

Thanks,
Xavi M.

**Comment by htvekov** [comment]
Hi' @xaviml 

Yep. v1.0 is quite ready 🙂

I haven't made any reference though to the actual documentation (jump link from examples page)
Perhaps you wanted to make this in another way, rearrange or otherwise change. So I left this untouched.

The documentation and the two extra files (picture and ttf file are also included)
The two links in documnetation should perhaps be renamed from my fork to your master branch (or is that done automatically ?)

That's it I believe, Xavi.

Ciao ! 🙋‍♂️

**Comment by xaviml** [comment]
Okay, thanks Henning. I will check it out and let you know if I have any questions.

Thank you for your contribution!!

Xavi M.

**Comment by htvekov** [comment]
Forgot to add an 'ambience' picture you perhaps can use.
This could be used as 'header' for both Sonos documentations perhaps.

Sorry about the crappy casing. I took what was left in the drawer whre the SSD1309 could fit 😉😁

**Comment by htvekov** [comment]
Hope you like it, Xavi and that other users find the documentation usefull in some way.

I'm already working on some of the improvements I wanted to add.
Mainly turn on/off display and brightness control - via ESPHome switches/PIR's that are exposed to HA as well.

Working nicely. Only 'fryed' two PIR's in the process so far... 😆😉

**Comment by xaviml** [comment]
Hey Henning!

Such detailed documentation, bravo! I might consider doing something similar.. wonder if it would work well with my Google Home Mini, but I think so, Home Assistant know what is playing, so that is a start.

I fixed some things on the yaml configuration since the {{ and {% from the templating where messing up with the real Jekyll (tool I use for documentation) template system. I also added the picture you beforementioned on top of the both Sonos pages.

Here is the link: https://xaviml.github.io/controllerx/examples/sonos-display

Again, thank you for your awesome work!

**Comment by htvekov** [comment]
Hi' Xavi.

Checked the link - looks great 👍
Hope it will be checked out by the community and that some will find the documentation usefull - if not for full build, then for bits and ideas 🙂

Can I format templates differently for future PR's, so you won't have to reformat at your end ?

Your very welcome, Xavi 😎

Ciao !

**Comment by xaviml** [comment]
Thanks Henning for offering, but I think we work better if you use StackEdit to have the documentation as you expect it to be. If you worry about the formatting, you will get crazy because I had to replace `{{` for `{{ "{{" }}`, so you will get a headache with that many curly braces :face_with_thermometer:. I could handle it easily by just using replace functionality from my IDE.

**Pull request merged**
